package ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Toolkit;
import clases.Conexión;
import java.sql.*;
import javax.swing.WindowConstants;

public class Administrador extends javax.swing.JFrame {

    public static int SesiónUsuario;
    String usuario, NombreUsuario;

    public Administrador() {
        initComponents();
        SesiónUsuario = 1;
        usuario = Login.usuario;

        setTitle("Administrador - Sesión de " + usuario);
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(614, 485);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        ImageIcon ImagenFondo = new ImageIcon("src/images/fondo.jpg", "Imagen de fondo");
        Icon LogoFondo = new ImageIcon(ImagenFondo.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(),
                Image.SCALE_DEFAULT));
        lblFondo.setIcon(LogoFondo);
        this.repaint();

        try {
            Connection conexión = Conexión.Conexión_BD();
            PreparedStatement consulta = conexión.prepareStatement(
                    "select nombre_usuario from usuarios where username = ?");
            consulta.setString(1, usuario);
            ResultSet ResultadoConsulta = consulta.executeQuery();

            if (ResultadoConsulta.next() == true) {
                NombreUsuario = ResultadoConsulta.getString(1);
                lblNombreUsuario.setText("Bienvenido(a) " + NombreUsuario);
            }
        } catch (SQLException e) {
            System.err.println("Error de conexión en la Interfaz Administrador: " + e);
        }
    }

    @Override
    public Image getIconImage() {
        Image Icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return Icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreUsuario = new javax.swing.JLabel();
        btnRegistrarProductos = new javax.swing.JButton();
        btnGestionarUsuarios = new javax.swing.JButton();
        btnAgregarUsuarios = new javax.swing.JButton();
        btnVistaVendedor = new javax.swing.JButton();
        btnAcercaDe = new javax.swing.JButton();
        lblFooter = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreUsuario.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(0, 102, 255));
        lblNombreUsuario.setText("jLabel1");
        getContentPane().add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 540, 30));

        btnRegistrarProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnRegistrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 120, 120));

        btnGestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_gestionarusuarios.png"))); // NOI18N
        btnGestionarUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnGestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGestionarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 120, 120));

        btnAgregarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_agregarusuario.png"))); // NOI18N
        btnAgregarUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnAgregarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, 120));

        btnVistaVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_vistavendedor.png"))); // NOI18N
        btnVistaVendedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnVistaVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaVendedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnVistaVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 120, 120));

        btnAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_acercade.png"))); // NOI18N
        btnAcercaDe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(btnAcercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 120, 120));

        lblFooter.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        lblFooter.setText("Desarrollado por CódigoByte © - Gianmarco Contreras Pumamango");
        getContentPane().add(lblFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 360, 20));

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel3.setText("Agregar Usuarios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel4.setText("Administrar Usuarios");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel5.setText("-------------------------");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel6.setText("Vista Vendedor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel7.setText("Acerca De");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, -1));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 614, 485));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuariosActionPerformed
        RegistrarUsuarios RegUsuarios = new RegistrarUsuarios();
        RegUsuarios.setVisible(true);        
    }//GEN-LAST:event_btnAgregarUsuariosActionPerformed

    private void btnGestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarUsuariosActionPerformed
        GestionarUsuarios GestUsuarios = new GestionarUsuarios();
        GestUsuarios.setVisible(true);        
    }//GEN-LAST:event_btnGestionarUsuariosActionPerformed

    private void btnVistaVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaVendedorActionPerformed
        Vendedor vendedor = new Vendedor();
        vendedor.setVisible(true);
    }//GEN-LAST:event_btnVistaVendedorActionPerformed

    private void btnRegistrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProductosActionPerformed

    }//GEN-LAST:event_btnRegistrarProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcercaDe;
    private javax.swing.JButton btnAgregarUsuarios;
    private javax.swing.JButton btnGestionarUsuarios;
    private javax.swing.JButton btnRegistrarProductos;
    private javax.swing.JButton btnVistaVendedor;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
