package ventanas;

import java.sql.*;
import clases.Conexión;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class InformaciónProductos extends javax.swing.JFrame {

    String usuario;
    int ID_Producto;

    public InformaciónProductos() {
        initComponents();
        usuario = Login.usuario;
        ID_Producto = GestionarProductos.ID_Producto;

        setSize(550, 500);
        setResizable(false);
        setTitle("Actualización de producto - Sesión de " + usuario);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon ImagenFondo = new ImageIcon("src/images/fondo.jpg");
        Icon IconoFondo = new ImageIcon(ImagenFondo.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(),
                Image.SCALE_DEFAULT));
        lblFondo.setIcon(IconoFondo);
        this.repaint();

        //Realizamos la consulta a la base de datos para llenar la información de los controles
        try {
            Connection conexión = Conexión.Conexión_BD();
            PreparedStatement consulta = conexión.prepareStatement(
                    "select * from productos where id_producto = ?");
            consulta.setInt(1, ID_Producto);
            ResultSet ResultadoConsulta = consulta.executeQuery();

            if (ResultadoConsulta.next() == true) {
                txtNombreProducto.setText(ResultadoConsulta.getString("nombre_producto"));
                txtMarca.setText(ResultadoConsulta.getString("marca"));
                txtPrecio.setText(Float.toString(ResultadoConsulta.getFloat("precio")));
                txtÚtimaModificación.setText(ResultadoConsulta.getString("ultima_modificacion"));
                pnObservaciones.setText(ResultadoConsulta.getString("observaciones"));
                txtStockDisponible.setText(ResultadoConsulta.getString("stock"));                
//                cmbAgregarStock.setSelectedItem(ResultadoConsulta.getString("stock"));

                String día;
                int mes, annio;
                día = String.valueOf(ResultadoConsulta.getInt("dia_registro"));
                mes = ResultadoConsulta.getInt("mes_registro");
                annio = ResultadoConsulta.getInt("annio_registro");
                txtFechaRegistro.setText(día + " de " + mes + " del " + annio);
            }

        } catch (SQLException e) {
            System.err.println("ERROR al cargar la información del producto. " + e);
            JOptionPane.showMessageDialog(null, "ERROR al cargar la información del producto, contacte con el administrador");
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnObservaciones = new javax.swing.JTextPane();
        lblTítulo = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblAgregarStock = new javax.swing.JLabel();
        cmbAgregarStock = new javax.swing.JComboBox<>();
        lblUltimaModificacion = new javax.swing.JLabel();
        txtÚtimaModificación = new javax.swing.JTextField();
        lblObservaciones = new javax.swing.JLabel();
        btnActualizarProducto = new javax.swing.JButton();
        lblFechaRegistro = new javax.swing.JLabel();
        txtFechaRegistro = new javax.swing.JTextField();
        lblFooter = new javax.swing.JLabel();
        lblStockDisponible = new javax.swing.JLabel();
        txtStockDisponible = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(pnObservaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 250, 110));

        lblTítulo.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblTítulo.setText("Actualización de producto");
        getContentPane().add(lblTítulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        lblNombreProducto.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblNombreProducto.setText("Nombre del producto:");
        getContentPane().add(lblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtNombreProducto.setBackground(new java.awt.Color(102, 153, 255));
        txtNombreProducto.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtNombreProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, -1));

        lblMarca.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblMarca.setText("Marca:");
        getContentPane().add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txtMarca.setBackground(new java.awt.Color(102, 153, 255));
        txtMarca.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtMarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, -1));

        lblPrecio.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblPrecio.setText("Precio:");
        getContentPane().add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtPrecio.setBackground(new java.awt.Color(102, 153, 255));
        txtPrecio.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, -1));

        lblAgregarStock.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblAgregarStock.setText("Agregar stock:");
        getContentPane().add(lblAgregarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        cmbAgregarStock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));
        getContentPane().add(cmbAgregarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        lblUltimaModificacion.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblUltimaModificacion.setText("Última Modificación por:");
        getContentPane().add(lblUltimaModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        txtÚtimaModificación.setEditable(false);
        txtÚtimaModificación.setBackground(new java.awt.Color(102, 153, 255));
        txtÚtimaModificación.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtÚtimaModificación.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtÚtimaModificación.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(txtÚtimaModificación, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 180, -1));

        lblObservaciones.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblObservaciones.setText("Observaciones:");
        getContentPane().add(lblObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        btnActualizarProducto.setBackground(new java.awt.Color(255, 153, 255));
        btnActualizarProducto.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnActualizarProducto.setText("Actualizar Producto");
        btnActualizarProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 150, 35));

        lblFechaRegistro.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblFechaRegistro.setText("Fecha de registro:");
        getContentPane().add(lblFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        txtFechaRegistro.setEditable(false);
        txtFechaRegistro.setBackground(new java.awt.Color(102, 153, 255));
        txtFechaRegistro.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtFechaRegistro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(txtFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 180, -1));

        lblFooter.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        lblFooter.setText("Desarrollado por CódigoByte © - Gianmarco Contreras Pumamango");
        getContentPane().add(lblFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        lblStockDisponible.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblStockDisponible.setText("Stock disponible:");
        getContentPane().add(lblStockDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        txtStockDisponible.setEditable(false);
        txtStockDisponible.setBackground(new java.awt.Color(102, 153, 255));
        txtStockDisponible.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtStockDisponible.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStockDisponible.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(txtStockDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 110, -1));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProductoActionPerformed

        String observaciones;
        float precio;
        int StockDisponible, StockAgregado, validación = 0;

        precio = Float.parseFloat(txtPrecio.getText().trim());
        StockDisponible = Integer.parseInt(txtStockDisponible.getText());
        StockAgregado = Integer.parseInt(cmbAgregarStock.getSelectedItem().toString());
        observaciones = pnObservaciones.getText();

        if (txtPrecio.getText().trim().equals("")) {
            txtPrecio.setBackground(Color.red);
            validación = +1;
        }
        if (observaciones.equals("")) {
            pnObservaciones.setText("Sin observaciones");
        }

        if (validación == 0) {

            try {
                //Realizamos la actualización en la BD de los campos editados por el usuario
                Connection conexión = Conexión.Conexión_BD();
                PreparedStatement consulta = conexión.prepareStatement(
                        "update productos set precio = ?, stock = ?, ultima_modificacion = ?, observaciones = ? "
                        + "where id_producto = ?");

                consulta.setFloat(1, precio);
                consulta.setInt(2, StockDisponible + StockAgregado);
                consulta.setString(3, usuario);
                consulta.setString(4, observaciones);
                consulta.setInt(5, ID_Producto);
                consulta.executeUpdate();
                conexión.close();

                Limpiar();
                Iluminar();
                JOptionPane.showMessageDialog(null, "Actualización exitosa");
                this.dispose();

            } catch (SQLException e) {
                System.err.println("ERROR al actualizar producto. " + e);
                JOptionPane.showMessageDialog(null, "ERROR al actualizar producto, contacte con el administrador");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos");
        }

    }//GEN-LAST:event_btnActualizarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformaciónProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformaciónProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformaciónProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformaciónProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformaciónProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarProducto;
    private javax.swing.JComboBox<String> cmbAgregarStock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregarStock;
    private javax.swing.JLabel lblFechaRegistro;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStockDisponible;
    private javax.swing.JLabel lblTítulo;
    private javax.swing.JLabel lblUltimaModificacion;
    private javax.swing.JTextPane pnObservaciones;
    private javax.swing.JTextField txtFechaRegistro;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStockDisponible;
    private javax.swing.JTextField txtÚtimaModificación;
    // End of variables declaration//GEN-END:variables

    public void Limpiar() {
        txtFechaRegistro.setText("");
        txtMarca.setText("");
        txtNombreProducto.setText("");
        txtPrecio.setText("");
        txtÚtimaModificación.setText("");
    }

    public void Iluminar() {
        txtPrecio.setBackground(Color.green);
        txtStockDisponible.setBackground(Color.green);
        cmbAgregarStock.setBackground(Color.green);
        pnObservaciones.setBackground(Color.green);
    }
}
