/*
 * Software de Gestión de Ventas e Inventario
 * AngitaSystem v1.0
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexión;
import javax.swing.JOptionPane;

/*
 *@author GIANMARCO CONTRERAS PUMAMANGO - CÓDIGO BYTE
 */
public class Login extends javax.swing.JFrame {

    public static String usuario = "";
    public static int ID_Usuario;
    String contraseña = "";

    public Login() {
        initComponents();
        setSize(500, 650);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Acceso al Software");

        ImageIcon ImagenFondo = new ImageIcon("src/images/fondo.jpg", "Imagen de fondo");
        Icon LogoFondo = new ImageIcon(ImagenFondo.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(),
                Image.SCALE_DEFAULT));
        lblFondo.setIcon(LogoFondo);
        this.repaint();

        ImageIcon ImagenLogo = new ImageIcon("src/images/bodega.jpg", "Imagen de Login");
        Icon IconoLogo = new ImageIcon(ImagenLogo.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(),
                Image.SCALE_DEFAULT));
        lblLogo.setIcon(IconoLogo);
        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image IconoSistema = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return IconoSistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        lblFooter = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bodega.jpg"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 330, 310));

        txtUsuario.setBackground(new java.awt.Color(102, 153, 255));
        txtUsuario.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 420, 200, -1));

        txtContraseña.setBackground(new java.awt.Color(102, 153, 255));
        txtContraseña.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 485, 200, -1));

        btnIngresar.setBackground(new java.awt.Color(153, 153, 255));
        btnIngresar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnIngresar.setText("INGRESAR");
        btnIngresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 170, -1));

        lblFooter.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        lblFooter.setText("Desarrollado por CódigoByte © - Gianmarco Contreras Pumamango");
        getContentPane().add(lblFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, -1, -1));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        usuario = txtUsuario.getText().trim();
        contraseña = txtContraseña.getText().trim();

        //Validamos la autenticación del usuario al ingresar al sistema
        if (usuario.equals("") || contraseña.equals("")) {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        } else {
            try {
                Connection conexión = Conexión.Conexión_BD();
                PreparedStatement consulta = conexión.prepareStatement(
                        "select tipo_nivel, estatus from usuarios where username = ? and password = ?");
                consulta.setString(1, usuario); //Mandamos los datos a la consulta
                consulta.setString(2, contraseña);
                ResultSet ResultadoConsulta = consulta.executeQuery();

                if (ResultadoConsulta.next() == true) {
                    String tipo_nivel = ResultadoConsulta.getString(1); //Se obtiene el primer y segundo string de la consulta
                    String estatus = ResultadoConsulta.getString(2);
                    
                    if (estatus.equals("Activo")) {
                        //Código agregado de mi ingenio
                        PreparedStatement consulta2 = conexión.prepareStatement(
                                "select id_usuario from usuarios where username = ?");
                        consulta2.setString(1, usuario);
                        ResultSet ResultadoConsulta2 = consulta2.executeQuery();

                        if (ResultadoConsulta2.next() == true) {
                            ID_Usuario = ResultadoConsulta2.getInt(1);
                        }
                        //******************************************************************                        
                        switch (tipo_nivel) {
                            case "Administrador":
                                new Administrador().setVisible(true);
                                break;
                            case "Vendedor":
                                new Vendedor().setVisible(true);
                                break;
                        }
                    } else if (estatus.equals("Inactivo")) {
                        System.err.println("Usuario dado de baja");
                        JOptionPane.showMessageDialog(null, "Su usuario esta inactivo, contacte con el Admministrador");
                        txtUsuario.setText("");
                        txtContraseña.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Datos incorrectos");
                    txtUsuario.setText("");
                    txtContraseña.setText("");
                }
            } catch (SQLException e) {
                System.err.println("ERROR en acceso al sisema: " + e);
                JOptionPane.showMessageDialog(null, "Error en acceso al sistema, contacte con el administrador");
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
