package ventanas;

import java.sql.*;
import clases.Conexión;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class RegistrarUsuarios extends javax.swing.JFrame {

    String usuario = Login.usuario;

    public RegistrarUsuarios() {
        initComponents();
        setResizable(false);
        setSize(530, 390);
        setLocationRelativeTo(null);
        setTitle("Registrar nuevo usuario - Sesión de " + usuario);

        //Para que al cerrar la ventana actual, el programa no finalize
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon ImagenFondo = new ImageIcon("src/images/fondo.jpg");
        Icon IconoFondo = new ImageIcon(ImagenFondo.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(),
                Image.SCALE_DEFAULT));
        lblFondo.setIcon(IconoFondo);
        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        cmbPermisos = new javax.swing.JComboBox<>();
        btnRegistrarUsuarios = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setText("Registro de usuarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 230, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtNombre.setBackground(new java.awt.Color(102, 153, 255));
        txtNombre.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("Em@il:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtEmail.setBackground(new java.awt.Color(102, 153, 255));
        txtEmail.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Permisos de:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        txtCelular.setBackground(new java.awt.Color(102, 153, 255));
        txtCelular.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtCelular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("Username:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        txtUsername.setBackground(new java.awt.Color(102, 153, 255));
        txtUsername.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 180, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setText("Password:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jPass.setBackground(new java.awt.Color(102, 153, 255));
        getContentPane().add(jPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 180, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setText("Celular:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        cmbPermisos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor" }));
        getContentPane().add(cmbPermisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, -1));

        btnRegistrarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_agregarusuario.png"))); // NOI18N
        btnRegistrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 120, 80));

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel8.setText("Desarrollado por CodigoByte  © - Gianmarco Contreras Pumamango");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuariosActionPerformed
        String nombre, email, celular, username, password, Spermisos = "";
        int Ipermisos, validar = 0;

        nombre = txtNombre.getText().trim();
        email = txtEmail.getText().trim();
        celular = txtCelular.getText().trim();
        username = txtUsername.getText().trim();
        password = jPass.getText().trim();
        Ipermisos = cmbPermisos.getSelectedIndex() + 1;

        if (nombre.equals("")) {
            txtNombre.setBackground(Color.red);
            validar += 1; //Utilizamos esta variable como una condición para evitar que el programa se siga ejecutando
        }
        if (email.equals("")) {
            txtEmail.setBackground(Color.red);
            validar += 1;
        }
        if (celular.equals("")) {
            txtCelular.setBackground(Color.red);
            validar += 1;
        }
        if (username.equals("")) {
            txtUsername.setBackground(Color.red);
            validar += 1;
        }
        if (password.equals("")) {
            jPass.setBackground(new Color(255, 0, 0));
            validar += 1;
        }

        if (Ipermisos == 1) {
            Spermisos = "Administrador";
        } else if (Ipermisos == 2) {
            Spermisos = "Vendedor";
        }

        try {
            Connection conexión = Conexión.Conexión_BD();
            PreparedStatement consulta = conexión.prepareStatement(
                    "select username from usuarios where username = ?");
            consulta.setString(1, username);
            ResultSet ResultadoConsulta = consulta.executeQuery();

            if (ResultadoConsulta.next() == true) {
                txtUsername.setBackground(new Color(255, 0, 0));
                JOptionPane.showMessageDialog(null, "Nombre de usuario no disponible");
                conexión.close();
            } else {
                conexión.close();

                if (validar == 0) {
                    try {
                        Connection conexión2 = Conexión.Conexión_BD();
                        PreparedStatement consulta2 = conexión2.prepareStatement(
                                "insert into usuarios values (?,?,?,?,?,?,?,?,?)");

                        //Le pasamos los parámetros a la base de datos para que realize la consulta
                        consulta2.setInt(1, 0);
                        consulta2.setString(2, nombre);
                        consulta2.setString(3, email);
                        consulta2.setString(4, celular);
                        consulta2.setString(5, username);
                        consulta2.setString(6, password);
                        consulta2.setString(7, Spermisos);
                        consulta2.setString(8, "Activo");
                        consulta2.setString(9, usuario);

                        consulta2.executeUpdate();
                        conexión2.close();
                        Vaciar();

                        txtCelular.setBackground(Color.green);
                        txtEmail.setBackground(Color.green);
                        txtNombre.setBackground(Color.green);
                        txtUsername.setBackground(Color.green);
                        jPass.setBackground(Color.green);

                        JOptionPane.showMessageDialog(null, "Registro con éxito");
                        this.dispose(); //Eliminamos objetos y liberamos recursos del sistema

                    } catch (SQLException e) {
                        System.err.println("Error al registrar usuario " + e);
                        JOptionPane.showMessageDialog(null, "ERROR al registrar usuario, contacte con el administrador");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
                }
            }
        } catch (SQLException e) {
            System.err.println("Error en validar el nombre de usuario" + e);
            JOptionPane.showMessageDialog(null, "ERROR al registrar el nombre de usuario, contacte con el administrador !!!");
        }
    }//GEN-LAST:event_btnRegistrarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarUsuarios;
    private javax.swing.JComboBox<String> cmbPermisos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    public void Vaciar() {
        txtCelular.setText("");
        txtEmail.setText("");
        txtNombre.setText("");
        txtUsername.setText("");
        jPass.setText("");
        cmbPermisos.setSelectedIndex(0);
    }
}
