package ventanas;

import java.sql.*;
import clases.Conexión;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class RegistrarProductos extends javax.swing.JFrame {

    public static int ID_Usuario;
    String usuario;

    public RegistrarProductos() {
        initComponents();
        ID_Usuario = Login.ID_Usuario;
        usuario = Login.usuario;
        setTitle("Registro de producto - Sesión de " + usuario);
        txtÚtimaModificación.setText(usuario);
        setSize(550, 500);
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon ImagenFondo = new ImageIcon("src/images/fondo.jpg");
        Icon IconoFondo = new ImageIcon(ImagenFondo.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(),
                Image.SCALE_DEFAULT));
        lblFondo.setIcon(IconoFondo);
        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneObservaciones = new javax.swing.JTextPane();
        lblTítulo = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        lblRegistradoPor = new javax.swing.JLabel();
        txtÚtimaModificación = new javax.swing.JTextField();
        lblObservaciones = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        btnRegistrarProducto = new javax.swing.JButton();
        lblFooter = new javax.swing.JLabel();
        cmbStock = new javax.swing.JComboBox<>();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jTextPaneObservaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 250, 160));

        lblTítulo.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblTítulo.setText("Registro de producto");
        getContentPane().add(lblTítulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        txtNombreProducto.setBackground(new java.awt.Color(102, 153, 255));
        txtNombreProducto.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtNombreProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, -1));

        lblMarca.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblMarca.setText("Marca:");
        getContentPane().add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txtMarca.setBackground(new java.awt.Color(102, 153, 255));
        txtMarca.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtMarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, -1));

        lblPrecio.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblPrecio.setText("Precio:");
        getContentPane().add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtPrecio.setBackground(new java.awt.Color(102, 153, 255));
        txtPrecio.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, -1));

        lblStock.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblStock.setText("Stock:");
        getContentPane().add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        lblRegistradoPor.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblRegistradoPor.setText("Registrado por:");
        getContentPane().add(lblRegistradoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        txtÚtimaModificación.setEditable(false);
        txtÚtimaModificación.setBackground(new java.awt.Color(102, 153, 255));
        txtÚtimaModificación.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        txtÚtimaModificación.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtÚtimaModificación.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(txtÚtimaModificación, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 180, -1));

        lblObservaciones.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblObservaciones.setText("Observaciones:");
        getContentPane().add(lblObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        lblNombreProducto.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblNombreProducto.setText("Nombre del producto:");
        getContentPane().add(lblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        btnRegistrarProducto.setBackground(new java.awt.Color(255, 153, 255));
        btnRegistrarProducto.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnRegistrarProducto.setText("Registrar Producto");
        btnRegistrarProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 150, 35));

        lblFooter.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        lblFooter.setText("Desarrollado por CódigoByte © - Gianmarco Contreras Pumamango");
        getContentPane().add(lblFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        cmbStock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "50", "100" }));
        getContentPane().add(cmbStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProductoActionPerformed
        String NombreProducto, marca, UltimaModificación, observaciones, precio, DíaRegistro, MesRegistro, AnnioRegistro;
        int stock, validación = 0;

        NombreProducto = txtNombreProducto.getText().trim();
        marca = txtMarca.getText().trim();
        precio = txtPrecio.getText().trim();
        stock = Integer.parseInt(String.valueOf(cmbStock.getSelectedItem())); //Convertimos el objeto devuelto a int
        UltimaModificación = usuario;
        observaciones = jTextPaneObservaciones.getText();

        Calendar calendario = Calendar.getInstance();

        //Convertimos el int devuelto a String, cualquiera de las 3 formas es válida
        DíaRegistro = String.valueOf(calendario.get(Calendar.DATE));
        MesRegistro = "" + (calendario.get(Calendar.MONTH) + 1);
        AnnioRegistro = Integer.toString(calendario.get(Calendar.YEAR));

        if (NombreProducto.equals("")) {
            txtNombreProducto.setBackground(Color.red);
            validación += 1;
        }
        if (marca.equals("")) {
            txtMarca.setBackground(Color.red);
            validación += 1;
        }
        if (UltimaModificación.equals("")) {
            txtÚtimaModificación.setBackground(Color.red);
            validación += 1;
        }
        if (precio.equals("")) {
            txtPrecio.setBackground(Color.red);
            validación += 1;
        }

        if (validación == 0) {

            try {
                Connection conexión = Conexión.Conexión_BD();
                PreparedStatement consulta = conexión.prepareStatement(
                        "insert into productos values (?,?,?,?,?,?,?,?,?,?,?)");
                consulta.setInt(1, 0);
                consulta.setInt(2, ID_Usuario);
                consulta.setString(3, NombreProducto);
                consulta.setString(4, marca);
                //setString indica que pasaremos  a la consulta un String y no que en la BD ese campo sea String
                consulta.setString(5, DíaRegistro); 
                consulta.setString(6, MesRegistro);
                consulta.setString(7, AnnioRegistro);
                consulta.setString(8, precio);
                consulta.setInt(9, stock);
                consulta.setString(10, UltimaModificación);
                consulta.setString(11, observaciones);

                consulta.executeUpdate();
                conexión.close();

                Limpiar();
                Iluminar();

                JOptionPane.showMessageDialog(null, "Registro exitoso");
                this.dispose();

            } catch (SQLException e) {
                System.err.println("ERROR al registrar producto. " + e);
                JOptionPane.showMessageDialog(null, "ERROR al registrar producto, contacte con el administrador");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos, excepto las observaciones que es opcional");
        }
    }//GEN-LAST:event_btnRegistrarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JComboBox<String> cmbStock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPaneObservaciones;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblRegistradoPor;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTítulo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtÚtimaModificación;
    // End of variables declaration//GEN-END:variables

    public void Limpiar() {
        txtMarca.setText("");
        txtNombreProducto.setText("");
        txtPrecio.setText("");
        txtÚtimaModificación.setText("");
        jTextPaneObservaciones.setText("");
        cmbStock.setSelectedIndex(0);
    }

    public void Iluminar() {
        txtMarca.setBackground(Color.green);
        txtNombreProducto.setBackground(Color.green);
        txtPrecio.setBackground(Color.green);
        txtÚtimaModificación.setBackground(Color.green);
        jTextPaneObservaciones.setBackground(Color.green);
        cmbStock.setBackground(Color.green);
    }
}
