package ventanas;

import java.sql.*;
import clases.Conexión;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class RestaurarPassword extends javax.swing.JFrame {

    String usuario = Login.usuario;
    String UsuarioConsultado = GestionarUsuarios.UsuarioConsultado;

    public RestaurarPassword() {
        initComponents();

        setSize(370, 330);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Restauración de password para " + UsuarioConsultado);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon ImagenFondo = new ImageIcon("src/images/fondo.jpg", "Imagen de fondo");
        Icon LogoFondo = new ImageIcon(ImagenFondo.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(),
                Image.SCALE_DEFAULT));
        lblFondo.setIcon(LogoFondo);
        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image IconoSistema = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return IconoSistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPass = new javax.swing.JPasswordField();
        jPassRepeat = new javax.swing.JPasswordField();
        btnRestaurarPassword = new javax.swing.JButton();
        lblFooter = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("Restaurar Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 170, 20));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Nuevo Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("Confirmar Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jPass.setBackground(new java.awt.Color(102, 153, 255));
        jPass.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(jPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 290, -1));

        jPassRepeat.setBackground(new java.awt.Color(102, 153, 255));
        jPassRepeat.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPassRepeat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        getContentPane().add(jPassRepeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 290, -1));

        btnRestaurarPassword.setBackground(new java.awt.Color(255, 153, 255));
        btnRestaurarPassword.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnRestaurarPassword.setText("RESTAURAR PASSWORD");
        btnRestaurarPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRestaurarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btnRestaurarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 200, 40));

        lblFooter.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        lblFooter.setText("Desarrollado por CódigoByte © - Gianmarco Contreras Pumamango");
        getContentPane().add(lblFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 350, 20));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestaurarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarPasswordActionPerformed
        String password, ConfirmarPass;

        password = jPass.getText().trim();
        ConfirmarPass = jPassRepeat.getText().trim();

        if (!password.equals("") && !ConfirmarPass.equals("")) {

            if (password.equals(ConfirmarPass)) {

                try {
                    Connection conexión = Conexión.Conexión_BD();
                    PreparedStatement consulta = conexión.prepareStatement(
                            "update usuarios set password = ? where username = ?");
                    consulta.setString(1, password);
                    consulta.setString(2, UsuarioConsultado);
                    consulta.executeUpdate();
                    conexión.close();

                    jPass.setBackground(Color.green);
                    jPassRepeat.setBackground(Color.green);
                    JOptionPane.showMessageDialog(null, "Password restaurado correctamente");
                    this.dispose();

                } catch (SQLException e) {
                    System.err.println("ERROR al restaurar el password. " + e);
                    JOptionPane.showMessageDialog(null, "ERROR al restaurar el password, contacte con el adminstrador");
                }

            } else {
                jPass.setBackground(Color.red);
                jPassRepeat.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Los passwords no coinciden");
                jPass.setText("");
                jPassRepeat.setText("");
            }

        } else if (password.equals("") && ConfirmarPass.equals("")) {
            jPass.setBackground(Color.red);
            jPassRepeat.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");

        } else if (password.equals("")) {
            jPass.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Debes ingresar el nuevo password");

        } else if (ConfirmarPass.equals("")) {
            jPassRepeat.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Debes confirmar el password");
        }
    }//GEN-LAST:event_btnRestaurarPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurarPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRestaurarPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JPasswordField jPassRepeat;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFooter;
    // End of variables declaration//GEN-END:variables
}
